### ISSUE TITLE
Filtering feeds. Posting full contents.

### ISSUE THREAD

**Issue by rsoorajs** [nikstar/greader#5]
Can you please add filter option ,like if the specific, keywords appears it have to publish,else not.

Also please make it for posting full contents, instead of short Description.we need to get full feed contents,thats why we are using the bot.but almost feed readers are just providing 2 lines of content and then a url for that.so please add an option for getting all the item description

**Comment by nikstar** [comment]
Hi @telegrambotdev 

Filtering feeds feels like something better done server-side. Looks like there are some services that do that, e.g. https://siftrss.com and http://feedrinse.com/index-old.php. I want to keep this client more general purpose.

Full content in feeds may include arbitrary HTML, and Telegram does not support that in messages. You'd have to strip all HTML tags, and this would look bad in many cases.
